version: '3.2'
services:
    app:
        container_name: refueling_node
        image: node:16
        volumes:
            - ./:/var/www/html:delegated
        links:
            - database
        ports:
            - 8085:3000
        env_file: ./.env
        environment:
            - DB_HOST=database
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
            - DB_NAME=$DB_NAME
            - DB_PORT=$DB_PORT
        stdin_open: true
        tty: true
    database:
        container_name: refueling_mongo
        image: mongo:5.0.2
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$DB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
        ports:
            - 7015:$DB_PORT
        volumes:
            - db:/data/db
volumes:
    db: